name: codingenv
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch=2.1
  - torchvision
  - pip
  - pip:
    - einops==0.8.2
    - timm==1.0.25
    - matplotlib
    - numpy
    - Pillow
    - tqdm
    - coremltools
